apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/naren9876/ticketing-app.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
